package org.gwtspringhibernate.reference.rlogman.server.data;

// Generated 23/08/2006 04:37:50 PM by Hibernate Tools 3.1.0.beta5

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Classification generated by hbm2java
 */
@Entity
@Table(name = "CLASSIFICATION", uniqueConstraints = {})
public class Classification
		implements java.io.Serializable {

	// Fields    

	private short classificationId;

	private String classificationName;

	private String description;

	private char mandatory;

	private char multiple;

	// Constructors

	/** default constructor */
	public Classification() {
	}

	/** minimal constructor */
	public Classification(short classificationId, String classificationName,
		char mandatory, char multiple) {
		this.classificationId = classificationId;
		this.classificationName = classificationName;
		this.mandatory = mandatory;
		this.multiple = multiple;
	}

	/** full constructor */
	public Classification(short classificationId, String classificationName,
		String description, char mandatory, char multiple) {
		this.classificationId = classificationId;
		this.classificationName = classificationName;
		this.description = description;
		this.mandatory = mandatory;
		this.multiple = multiple;
	}

	// Property accessors
	@Id
	@Column(name = "CLASSIFICATION_ID", unique = true, nullable = false, insertable = true, updatable = true, precision = 4, scale = 0)
	public short getClassificationId() {
		return this.classificationId;
	}

	public void setClassificationId(short classificationId) {
		this.classificationId = classificationId;
	}

	@Column(name = "CLASSIFICATION_NAME", unique = false, nullable = false, insertable = true, updatable = true, length = 80)
	public String getClassificationName() {
		return this.classificationName;
	}

	public void setClassificationName(String classificationName) {
		this.classificationName = classificationName;
	}

	@Column(name = "DESCRIPTION", unique = false, nullable = true, insertable = true, updatable = true)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "MANDATORY", unique = false, nullable = false, insertable = true, updatable = true, length = 1)
	public char getMandatory() {
		return this.mandatory;
	}

	public void setMandatory(char mandatory) {
		this.mandatory = mandatory;
	}

	@Column(name = "MULTIPLE", unique = false, nullable = false, insertable = true, updatable = true, length = 1)
	public char getMultiple() {
		return this.multiple;
	}

	public void setMultiple(char multiple) {
		this.multiple = multiple;
	}

}
